### ISSUE TITLE
Found 2 bugs

### ISSUE THREAD

**Issue by nevadeon** [42LeHavre/42LeHavreRoboZZle#3]
1) It's currently possible to change the instructions while the game is playing :

[Screencast from 27-04-2024 15:27:06.webm](https://github.com/42LeHavre/42LeHavreRoboZZle/assets/142907203/04923d74-e6ef-48c1-8c42-21c2de34db4c)

2) If the player selects an action and completes a level, he keeps the ability to place the last selected action even if its not available in the next level.
e.g. if the player select the f2 button and completes the level, even if in the next level there is no f2 function he can still place f2 actions.

[Screencast from 27-04-2024 15:28:15.webm](https://github.com/42LeHavre/42LeHavreRoboZZle/assets/142907203/45b252e6-18c3-4e59-a7fa-e864cc19d07e)

**Comment by DinoMalin** [comment]
Fixed ✅
